### ISSUE TITLE
Canonical website source

### ISSUE THREAD

**Issue by paddatrapper** [libretime/website#9]
I think we should keep the latest version of the docs in libretime/libretime. This ensures that PRs modifying features are tied to the documentation updates required to match. This is then copied over to this repo where it is deployed and different versions can be maintained

@jooola thoughts?

**Comment by jooola** [comment]
I agree, I just imported the current docs to make the website build again while working on this.

So the single source of truth for ANY documentation should be on the main branch, this means for the main branch and also for the 3.0.x branch.

I haven't figured out how to work with translated documentation, but that's another issue.
